# Generated by Django 5.2.1 on 2025-06-25 11:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Establishment Name')),
                ('year_established', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Established')),
                ('address_line', models.CharField(max_length=255, verbose_name='Street Address')),
                ('barangay', models.CharField(max_length=100, verbose_name='Barangay')),
                ('city', models.CharField(max_length=100, verbose_name='City/Municipality')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Establishment',
                'verbose_name_plural': 'Establishments',
                'ordering': ['-created_at'],
            },
        ),
    ]
