# Generated by Django 5.2.1 on 2025-07-05 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NatureOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Business Nature')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nature of Business',
                'verbose_name_plural': 'Nature of Business Options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Establishment Name')),
                ('year_established', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Established')),
                ('address_line', models.CharField(max_length=255, verbose_name='Street Address')),
                ('barangay', models.CharField(max_length=100, verbose_name='Barangay')),
                ('city', models.CharField(max_length=100, verbose_name='City/Municipality')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('postal_code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Postal Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('nature_of_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishments', to='establishment.natureofbusiness', verbose_name='Nature of Business')),
            ],
            options={
                'verbose_name': 'Establishment',
                'verbose_name_plural': 'Establishments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstablishmentPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.JSONField(help_text='GeoJSON format coordinates for the polygon', verbose_name='Polygon Coordinates')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polygon', to='establishment.establishment', verbose_name='Establishment')),
            ],
            options={
                'verbose_name': 'Establishment Polygon',
                'verbose_name_plural': 'Establishment Polygons',
                'ordering': ['-created_at'],
            },
        ),
    ]
