# Generated by Django 5.2.1 on 2025-06-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_alter_establishment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='nature_of_business',
            field=models.CharField(blank=True, choices=[('retail', 'Retail'), ('food', 'Food & Beverage'), ('service', 'Service'), ('manufacturing', 'Manufacturing'), ('hospitality', 'Hospitality'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], max_length=50, null=True, verbose_name='Nature of Business'),
        ),
    ]
