# Generated by Django 5.2.1 on 2025-07-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0003_establishment_nature_of_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='postal_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Postal Code'),
        ),
    ]
