# Generated by Django 5.2.1 on 2025-05-31 17:08

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=base.models.default_avatar, null=True, upload_to='avatars/'),
        ),
    ]
