# Generated by Django 5.2.1 on 2025-06-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('user_created', 'User Created'), ('password_reset', 'Password Reset'), ('status_changed', 'Status Changed'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('profile_updated', 'Profile Updated'), ('avatar_updated', 'Avatar Updated'), ('login', 'User Login'), ('logout', 'User Logout')], max_length=50),
        ),
    ]
