# Generated by Django 5.2.1 on 2025-06-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_activitylog_options_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
    ]
