# Generated by Django 5.2.1 on 2025-06-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_activitylog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('RA-6969', 'RA-6969'), ('RA-8749', 'RA-8749'), ('RA-9275', 'RA-9275'), ('RA-9003', 'RA-9003')], help_text='Applicable only for Inspector and Chief roles', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('chief', 'Chief'), ('inspector', 'Inspector')], default='inspector', max_length=20),
        ),
    ]
