# Generated by Django 5.2.1 on 2025-07-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_user_role_alter_user_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('division_chief', 'Division Chief'), ('eia_air_water_section_chief', 'EIA Air Water Section Chief'), ('toxic_hazardous_section_chief', 'Toxic Hazardous Section Chief'), ('solid_waste_section_chief', 'Solid Waste Section Chief'), ('eia_monitoring_unit_head', 'EIA Monitoring Unit Head'), ('air_quality_unit_head', 'Air Quality Unit Head'), ('water_quality_unit_head', 'Water Quality Unit Head'), ('eia_monitoring_personnel', 'EIA Monitoring Personnel'), ('air_quality_monitoring_personnel', 'Air Quality Monitoring Personnel'), ('water_quality_monitoring_personnel', 'Water Quality Monitoring Personnel'), ('toxic_chemicals_monitoring_personnel', 'Toxic Chemicals Monitoring Personnel'), ('solid_waste_monitoring_personnel', 'Solid Waste Monitoring Personnel')], default='eia_monitoring_personnel', max_length=50),
        ),
    ]
