# Generated by Django 5.2.1 on 2025-07-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
